#!/usr/bin/env python3
"""
CCAF101 The Beacon Owl brand asset generator.

Code-Is-Truth:
- Shape lives in OWL_16.
- Color lives in COLORS_LIGHT / COLORS_DARK.
- All SVG, PNG, and ICO outputs are generated from those two sources.

Usage:
    python3 generate_assets.py
"""

from __future__ import annotations

import argparse
import os
import shutil
import struct
import zlib


SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "output")



# Color slots:
# 0 = transparent
# 1 = Ink body / main silhouette
# 2 = Paper face / belly
# 3 = Beacon Amber eye / beak / feet
# 4 = Light eye highlight
# 5 = Dark Gray details
COLORS_LIGHT = {
    0: None,
    1: "#222222",
    2: "#F0EFEA",
    3: "#D4930D",
    4: "#FFFFFF",
    5: "#444444",
}

COLORS_DARK = {
    0: None,
    1: "#F0EFEA",
    2: "#222222",
    3: "#D4930D",
    4: "#FFFFFF",
    5: "#BBBBBB",
}


# 16x16 Beacon Owl.
#
# Core recognition:
# - ear tufts in rows 0-2
# - compact upright owl body
# - paper face disk / belly
# - single amber Beacon Eye in the center
# - small amber beak / feet
OWL_16 = [
    # 0 1 2 3 4 5 6 7 8 9 A B C D E F
    [0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0],  # 0: ear tufts
    [0,0,1,1,1,1,0,0,0,0,1,1,1,1,0,0],  # 1: upper head
    [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0],  # 2: head widest
    [0,1,1,2,2,2,2,2,2,2,2,2,1,1,1,0],  # 3: face disk top
    [1,1,2,2,2,2,2,2,2,2,2,2,2,1,1,0],  # 4: face disk
    [1,1,2,2,2,5,5,3,3,5,5,2,2,1,1,0],  # 5: single amber Beacon Eye
    [1,1,2,2,2,5,3,4,3,5,2,2,2,1,1,0],  # 6: eye highlight / ring
    [1,1,1,2,2,2,5,3,5,2,2,2,1,1,1,0],  # 7: lower face / beak
    [0,1,1,1,2,2,2,3,2,2,2,1,1,1,0,0],  # 8: beak / neck
    [0,1,1,1,1,2,2,2,2,2,1,1,1,1,0,0],  # 9: shoulders
    [0,1,5,1,1,2,2,2,2,2,1,1,5,1,0,0],  # A: wing detail
    [0,1,1,5,1,2,2,2,2,2,1,5,1,1,0,0],  # B: wing detail
    [0,0,1,1,1,1,2,2,2,1,1,1,1,0,0,0],  # C: body taper
    [0,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0],  # D: base
    [0,0,0,0,1,3,3,1,1,3,3,1,0,0,0,0],  # E: feet
    [0,0,0,0,0,3,0,0,0,0,3,0,0,0,0,0],  # F: foot tips
]


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    h = hex_color.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def save_file(path: str, content: str | bytes, binary: bool = False) -> None:
    mode = "wb" if binary else "w"
    encoding = None if binary else "utf-8"
    with open(path, mode, encoding=encoding) as f:
        f.write(content)
    size = os.path.getsize(path)
    if size < 1024:
        display = f"{size} B"
    else:
        display = f"{round(size / 1024, 1)} KB"
    print(f"  OK {os.path.basename(path):.<42s} {display}")


def pixel_rects(pixel_grid: list[list[int]], colors: dict[int, str | None], indent: str = "  ") -> str:
    rects = []
    for y, row in enumerate(pixel_grid):
        for x, val in enumerate(row):
            color = colors.get(val)
            if color:
                rects.append(
                    f'{indent}<rect x="{x}" y="{y}" width="1" height="1" fill="{color}"/>'
                )
    return "\n".join(rects)


def generate_icon_svg(pixel_grid: list[list[int]], colors: dict[int, str | None], display_size: int = 32) -> str:
    grid_size = len(pixel_grid)
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- CCAF101 The Beacon Owl. Generated by generate_assets.py. -->
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 {grid_size} {grid_size}"
     width="{display_size}" height="{display_size}"
     shape-rendering="crispEdges">
{pixel_rects(pixel_grid, colors)}
</svg>'''


def generate_full_logo_svg(
    pixel_grid: list[list[int]],
    colors: dict[int, str | None],
    text_color: str,
    dot_color: str,
) -> str:
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- CCAF101 The Beacon Owl full logo. Generated by generate_assets.py. -->
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 72 16"
     width="576" height="128"
     shape-rendering="crispEdges">
  <g>
{pixel_rects(pixel_grid, colors, indent="    ")}
  </g>
  <text x="19" y="11.5"
        font-family="'JetBrains Mono', 'SF Mono', 'Fira Code', 'Cascadia Code', monospace"
        font-weight="800"
        font-size="7.25"
        letter-spacing="0"
        fill="{text_color}">CCAF101</text>
  <circle cx="68.5" cy="11.5" r="0.8" fill="{dot_color}"/>
</svg>'''


def create_png(pixel_grid: list[list[int]], colors: dict[int, str | None], scale: int = 1) -> bytes:
    grid_size = len(pixel_grid)
    width = grid_size * scale
    height = grid_size * scale

    raw_data = b""
    for y in range(height):
        raw_data += b"\x00"
        src_y = y // scale
        for x in range(width):
            src_x = x // scale
            color = colors.get(pixel_grid[src_y][src_x])
            if color:
                r, g, b = hex_to_rgb(color)
                raw_data += struct.pack("BBBB", r, g, b, 255)
            else:
                raw_data += struct.pack("BBBB", 0, 0, 0, 0)

    def make_chunk(chunk_type: bytes, data: bytes) -> bytes:
        chunk = chunk_type + data
        crc = zlib.crc32(chunk) & 0xFFFFFFFF
        return struct.pack(">I", len(data)) + chunk + struct.pack(">I", crc)

    png = b"\x89PNG\r\n\x1a\n"
    png += make_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
    png += make_chunk(b"IDAT", zlib.compress(raw_data, 9))
    png += make_chunk(b"IEND", b"")
    return png


def create_ico(pixel_grid: list[list[int]], colors: dict[int, str | None]) -> bytes:
    images = [
        (16, create_png(pixel_grid, colors, scale=1)),
        (32, create_png(pixel_grid, colors, scale=2)),
        (48, create_png(pixel_grid, colors, scale=3)),
    ]

    ico = struct.pack("<HHH", 0, 1, len(images))
    offset = 6 + 16 * len(images)
    for size, data in images:
        ico += struct.pack(
            "<BBBBHHII",
            size,
            size,
            0,
            0,
            1,
            32,
            len(data),
            offset,
        )
        offset += len(data)

    for _, data in images:
        ico += data
    return ico


def generate(target_dir: str | None = None) -> None:
    svg_dir = os.path.join(OUTPUT_DIR, "SVG")
    png_dir = os.path.join(OUTPUT_DIR, "PNG")
    favicon_dir = os.path.join(OUTPUT_DIR, "favicon")

    ensure_dir(svg_dir)
    ensure_dir(png_dir)
    ensure_dir(favicon_dir)

    print("Generating Beacon Owl brand assets (Code-Is-Truth)")
    print(f"Local Output: {OUTPUT_DIR}")
    print()

    print("SVG...")
    save_file(os.path.join(svg_dir, "owl_logo_light.svg"), generate_icon_svg(OWL_16, COLORS_LIGHT))
    save_file(os.path.join(svg_dir, "owl_logo_dark.svg"), generate_icon_svg(OWL_16, COLORS_DARK))
    save_file(
        os.path.join(svg_dir, "owl_full_light.svg"),
        generate_full_logo_svg(OWL_16, COLORS_LIGHT, COLORS_LIGHT[1], COLORS_LIGHT[3]),
    )
    save_file(
        os.path.join(svg_dir, "owl_full_dark.svg"),
        generate_full_logo_svg(OWL_16, COLORS_DARK, COLORS_DARK[1], COLORS_DARK[3]),
    )

    print("PNG...")
    sizes = [(16, 1), (32, 2), (64, 4), (128, 8), (256, 16), (512, 32)]
    for px_size, scale in sizes:
        save_file(
            os.path.join(png_dir, f"owl_logo_light_{px_size}.png"),
            create_png(OWL_16, COLORS_LIGHT, scale=scale),
            binary=True,
        )
        save_file(
            os.path.join(png_dir, f"owl_logo_dark_{px_size}.png"),
            create_png(OWL_16, COLORS_DARK, scale=scale),
            binary=True,
        )

    print("Favicon...")
    fav_16 = os.path.join(favicon_dir, "favicon-16x16.png")
    fav_32 = os.path.join(favicon_dir, "favicon-32x32.png")
    fav_ico = os.path.join(favicon_dir, "favicon.ico")

    save_file(fav_16, create_png(OWL_16, COLORS_LIGHT, scale=1), binary=True)
    save_file(fav_32, create_png(OWL_16, COLORS_LIGHT, scale=2), binary=True)
    save_file(fav_ico, create_ico(OWL_16, COLORS_LIGHT), binary=True)

    if target_dir:
        abs_target = os.path.abspath(target_dir)
        ensure_dir(abs_target)
        print(f"\n🚀 Syncing assets to target frontend directory: {abs_target}")
        shutil.copy(fav_ico, os.path.join(abs_target, "favicon.ico"))
        shutil.copy(fav_16, os.path.join(abs_target, "favicon-16x16.png"))
        shutil.copy(fav_32, os.path.join(abs_target, "favicon-32x32.png"))
        shutil.copy(os.path.join(png_dir, "owl_logo_light_256.png"), os.path.join(abs_target, "apple-touch-icon.png"))
        shutil.copy(os.path.join(png_dir, "owl_logo_light_512.png"), os.path.join(abs_target, "android-chrome-512x512.png"))
        shutil.copy(os.path.join(svg_dir, "owl_logo_light.svg"), os.path.join(abs_target, "logo.svg"))
        print("✅ Synced: favicon.ico, favicon-16/32, apple-touch-icon, logo.svg to target!")

    print("\n✨ Done! All brand visual assets generated.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Beacon Owl Brand Asset Generator (Code-Is-Truth)")
    parser.add_argument("--out", "-o", help="Optional target directory (e.g. template/public) to sync web-ready assets directly")
    args = parser.parse_args()
    generate(target_dir=args.out)

